const DummyList = [
  {
    answerId: 1,
    user: "유저이름1",
    answerTitle: "타이틀1",
    answerContent: "질문내용1",
    answerRegistDate: new Date().getTime(),
    answerStatus: false,
  },
  {
    answerId: 2,
    user: "유저이름2",
    answerTitle: "타이틀2",
    answerContent: "질문내용2",
    answerRegistDate: new Date().getTime(),
    answerStatus: false,
  },
  {
    answerId: 3,
    user: "유저이름3",
    answerTitle: "타이틀3",
    answerContent: "질문내용3",
    answerRegistDate: new Date().getTime(),
    answerStatus: false,
  },
  {
    answerId: 4,
    user: "유저이름4",
    answerTitle: "타이틀4",
    answerContent: "질문내용4",
    answerRegistDate: new Date().getTime(),
    answerStatus: false,
  },
  {
    answerId: 5,
    user: "유저이름5",
    answerTitle: "타이틀5",
    answerContent: "질문내용5",
    answerRegistDate: new Date().getTime(),
    answerStatus: false,
  },
  {
    answerId: 6,
    user: "유저이름6",
    answerTitle: "타이틀6",
    answerContent: "질문내용6",
    answerRegistDate: new Date().getTime(),
    answerStatus: false,
  },
  {
    answerId: 7,
    user: "유저이름7",
    answerTitle: "타이틀7",
    answerContent: "질문내용7",
    answerRegistDate: new Date().getTime(),
    answerStatus: false,
  },
  {
    answerId: 8,
    user: "유저이름8",
    answerTitle: "타이틀8",
    answerContent: "질문내용8",
    answerRegistDate: new Date().getTime(),
    answerStatus: false,
  },
  {
    answerId: 9,
    user: "유저이름9",
    answerTitle: "타이틀9",
    answerContent: "질문내용9",
    answerRegistDate: new Date().getTime(),
    answerStatus: false,
  },
  {
    answerId: 10,
    user: "유저이름10",
    answerTitle: "타이틀10",
    answerContent: "질문내용10",
    answerRegistDate: new Date().getTime(),
    answerStatus: false,
  },
  {
    answerId: 11,
    user: "유저이름11",
    answerTitle: "타이틀11",
    answerContent: "질문내용11",
    answerRegistDate: new Date().getTime(),
    answerStatus: false,
  },
];

export default DummyList;
